### PR TITLE
[Not merge]Random multi shift

### PR DESCRIPTION
**Pull request by Zhaoyi-Yan**
I pull this request just for review. And it will not merge for the moment.
For this patch, it is about 2.5x time-consuming compared to the master branch.
The second shift searches neighbors in the neighbors of the corresponding pixels in the previous layer.
@tchaton , please have a look at this patch.

### CODE REVIEW

**Comment by Zhaoyi-Yan** [comment]
Also, This kind of 'U-Net' construction is very complicated to make a layer output two variables. That makes me using global variable to handle it. However, it should not work with multi-gpu training I think.

**Comment by Zhaoyi-Yan** [comment]
I optimize the random multi shift by reducing ~25% time-comsuming.

**Comment by Zhaoyi-Yan** [comment]
This is abandoned.

**Comment by tchaton** [comment]
Hello Yan,

I will come back on this monday and start again to work on it. Please, send me an email with everything you tried for me to know where you stand.

Best,
Thomas Chaton

**Pull request closed without merging**
